
theme: jekyll-theme-midnight
title: Constitutions of the World 
description: Finding the correlation between the prosperity and Constitutions of nations around the world  
menu: [
{'name': 'Home', 'Do Constitutions hold the key to prosperity?': 'index'},
{'name': 'Constitutions of the World', 'pagename': 'page1'},
{'name': 'Go there', 'pagename': 'page2'},
{'name': 'Yet Another page', 'pagename': 'page3'},
]
